name: NPM Publish

on:
  push:
    branches: [master]

jobs:
  publish-npm:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout project
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.PUSH_TOKEN }}

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version-file: .nvmrc

      - name: Setup
        run: npm ci

      - name: Test
        run: npm test

      - name: Build
        run: npm run build

      - name: Release
        run: npm run semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
