name: Pull Request

on:
  pull_request:
    branches: [master]

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout project
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version-file: .nvmrc
      - name: Setup
        run: npm ci
      - name: Build
        run: npm run build
      - name: Test
        run: npm run test
